require 'rails_helper'
require "rails-controller-testing"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe CustomersController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Customer. As you add validations to Customer, be sure to
  # adjust the attributes here as well.
  # Generate a random string once per example for consistency
  # Random string generated once per example
  let(:random_str) { SecureRandom.hex(4) }

  let!(:valid_attributes) do
    { name: "John_#{random_str}", email: "john_#{random_str}@example.com", vip: false, days_to_pay: 15 }
  end

  let(:new_attributes) do
    { name: "Jane_#{random_str}", email: "jane_#{random_str}@example.com" }
  end

  let(:invalid_attributes) do
    { name: "", email: "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CustomersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      Customer.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      customer = Customer.create! valid_attributes
      get :show, params: { id: customer.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      customer = Customer.create! valid_attributes
      get :edit, params: { id: customer.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      # let(:valid_attributes) { { name: 'John Doe', email: 'john@example.com', vip: false, days_to_pay: 15 } }
      it "creates a new Customer" do
        expect {
          post :create, params: { customer: valid_attributes }, session: valid_session
        }.to change(Customer, :count).by(1)
      end

      it "redirects to the created customer" do
        post :create, params: { customer: valid_attributes }, session: valid_session
        expect(response).to redirect_to(Customer.last)
      end
    end

    context "with invalid params" do
      it "renders a response with 422 status (i.e. to display the 'new' template')" do
        post :create, params: { customer: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
        expect(response).to render_template(:new)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      it "updates the requested customer" do
        customer = Customer.create! valid_attributes
        put :update, params: { id: customer.to_param, customer: new_attributes }, session: valid_session
        customer.reload
        expect(customer.name).to eq("Jane_#{random_str}")
        expect(customer.email).to eq("jane_#{random_str}@example.com")
      end

      it "redirects to the customer" do
        customer = Customer.create! valid_attributes
        put :update, params: { id: customer.to_param, customer: new_attributes }, session: valid_session
        expect(response).to redirect_to(customer)
      end
    end

    context "with invalid params" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        customer = Customer.create! valid_attributes
        put :update, params: { id: customer.to_param, customer: invalid_attributes }, session: valid_session
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested customer" do
      customer = Customer.create! valid_attributes
      expect {
        delete :destroy, params: { id: customer.to_param }, session: valid_session
      }.to change(Customer, :count).by(-1)
    end

    it "redirects to the customers list" do
      customer = Customer.create! valid_attributes
      delete :destroy, params: { id: customer.to_param }, session: valid_session
      expect(response).to redirect_to(customers_url)
    end
  end
end


# Our test suite is in excellent shape!
# All 12 examples passed, and your CustomersController spec is now fully stable. Your tests cover:
# All CRUD actions (index, show, new, edit, create, update, destroy)
# Valid and invalid parameters
# Redirects and HTTP status checks
# Randomized unique attributes to avoid collisions